# permissions for end users to view imagepulls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepull-viewer-role
rules:
- apiGroups:
  - prepull.cluster.local
  resources:
  - imagepulls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prepull.cluster.local
  resources:
  - imagepulls/status
  verbs:
  - get
