
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - prepull.cluster.local
  resources:
  - imagepulls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prepull.cluster.local
  resources:
  - imagepulls/finalizers
  verbs:
  - update
- apiGroups:
  - prepull.cluster.local
  resources:
  - imagepulls/status
  verbs:
  - get
  - patch
  - update
